from Container import Container

class PreliminaryContainer(Container):
    def __init__(self, path: str, mode: str, variables: dict):
        branches = {
            "emeas":            {"variable": variables["emeas"],},
            "demeas":           {"variable": variables["demeas"],},
            "runnum":           {"variable": variables["runnum"],},
            "evnum":            {"variable": variables["evnum"],},
            "nt_total":         {"variable": variables["nt_total"],},
            "ecaltot":          {"variable": variables["ecaltot"],},
            "ecalneu":          {"variable": variables["ecalneu"],},
            "psumch":           {"variable": variables["psumch"],},
            "psumnu":           {"variable": variables["psumnu"],},
            "nv_total":         {"variable": variables["nv_total"],},
            "nt":               {"variable": variables["nt"],},
            "tnhit":            {"variable": variables["tnhit"],},
            "tlength":          {"variable": variables["tlength"],},
            "tphi":             {"variable": variables["tphi"],},
            "tth":              {"variable": variables["tth"],},
            "tptot":            {"variable": variables["tptot"],},
            "tphiv":            {"variable": variables["tphiv"],},
            "tthv":             {"variable": variables["tthv"],},
            "tptotv":           {"variable": variables["tptotv"],},
            "trho":             {"variable": variables["trho"],},
            "tdedx":            {"variable": variables["tdedx"],},
            "tz":               {"variable": variables["tz"],},
            "tchi2r":           {"variable": variables["tchi2r"],},
            "tchi2z":           {"variable": variables["tchi2z"],},
            "tchi2ndf":         {"variable": variables["tchi2ndf"],},
            "tcharge":          {"variable": variables["tcharge"],},
            "ten":              {"variable": variables["ten"],},
            "tfc":              {"variable": variables["tfc"],},
            "tenlxe":           {"variable": variables["tenlxe"],},
            "tlengthlxe":       {"variable": variables["tlengthlxe"],},
            "tenslxe_layers":   {"variable": variables["tenslxe_layers"],},
            "tencsi":           {"variable": variables["tencsi"],},
            "tenbgo":           {"variable": variables["tenbgo"],},
            "tclth":            {"variable": variables["tclth"],},
            "tclphi":           {"variable": variables["tclphi"],},
            "terr":             {"variable": variables["terr"],},
            "tindlxe":          {"variable": variables["tindlxe"],},
            "txyzatcl":         {"variable": variables["txyzatcl"],},
            "txyzatlxe":        {"variable": variables["txyzatlxe"],},
            "tenconv":          {"variable": variables["tenconv"],},
            "ntlxe_total":      {"variable": variables["ntlxe_total"],},
            "ntlxe":            {"variable": variables["ntlxe"],},
            "ntlxelayers":      {"variable": variables["ntlxelayers"],},
            "tlxenhit":         {"variable": variables["tlxenhit"],},
            "tlxelength":       {"variable": variables["tlxelength"],},
            "tlxededx":         {"variable": variables["tlxededx"],},
            "tlxeir":           {"variable": variables["tlxeir"],},
            "tlxeitheta":       {"variable": variables["tlxeitheta"],},
            "tlxeiphi":         {"variable": variables["tlxeiphi"],},
            "tlxevtheta":       {"variable": variables["tlxevtheta"],},
            "tlxevphi":         {"variable": variables["tlxevphi"],},
            "tlxechi2":         {"variable": variables["tlxechi2"],},
            "tlxesen":          {"variable": variables["tlxesen"],},
            "tlxesen_layers":   {"variable": variables["tlxesen_layers"],},
        }
        Container.__init__(self, path, mode, branches)
