from Base.Container import Container

class FinalContainer(Container):
    def __init__(self, path: str, mode: str, variables):
        branches = [
            "nt",
            "ntlxe",
            "nph",
            
            "emeas",
            "demeas",
            "xbeam",
            "ybeam",
            "runnum",
            "evnum",
            "ecaltot",
            "ecalneu",
            "psumch",
            "psumnu",
            "nt_total",
            "nv_total",
            "ntlxe_total",
            "tnhit",
            "tlength",
            "tphi",
            "tth",
            "tptot",
            "tphiv",
            "tthv",
            "tptotv",
            "trho",
            "tdedx",
            "tz",
            "tchi2r",
            "tchi2z",
            "tchi2ndf",
            "tcharge",
            "tt0",
            "tant",
            "ten",
            "tfc",
            "tenlxe",
            "tlengthlxe",
            "ntlxelayers",
            "tenslxe_layers",
            "tencsi",
            "tenbgo",
            "tclth",
            "tclphi",
            "terr",
            "terr0",
            "tindlxe",
            "txyzatcl",
            "txyzatlxe",
            "tenconv",
            "tlxenhit",
            "tlxelength",
            "tlxededx",
            "tlxeir",
            "tlxeitheta",
            "tlxeiphi",
            "tlxevtheta",
            "tlxevphi",
            "tlxechi2",
            "tlxesen",
            "tlxesen_layers",
            "finalstate_id",

            "DeltaE",
            "TotalP",
            "KpKmPipPimLklhd",
            "KpTrackIndex",
            "KmTrackIndex",
            "PipTrackIndex",
            "PimTrackIndex",
            "KpKmPipPimKinfitChi2",
            "KpKmPipPimKinfitKpTrack",
            "KpKmPipPimKinfitKmTrack",
            "KpKmPipPimKinfitPipTrack",
            "KpKmPipPimKinfitPimTrack",
            "PipPimPipPimKinfitChi2",
            "PipPimPipPimKinfitPip0Track",
            "PipPimPipPimKinfitPim0Track",
            "PipPimPipPimKinfitPip1Track",
            "PipPimPipPimKinfitPim1Track",
            
            "PipPimPipPimMissMass",
        ]
        Container.__init__(self, path, mode, {branch: variables[branch] for branch in set(branches) & set(variables)})
